description = "Explain PersonalManager's task recommendation logic and decision-making process"
prompt = """
You are executing PersonalManager's 'explain' command which provides detailed insights into the AI-driven recommendation system.

COMMAND TO EXECUTE: ./bin/pm-local explain

Since you cannot directly execute shell commands, please:

1. Use read_file to examine the recommendation engine code:
   - src/pm/engines/recommendation_engine.py
   - src/pm/engines/intelligent_analysis_engine.py
   - src/pm/agents/gtd_agent.py

2. Analyze and explain the recommendation logic:
   - Multiple productivity framework integration (GTD, 4DX, OKR, Atomic Habits, etc.)
   - Scoring algorithms and weighting systems
   - Context detection and filtering
   - Energy matching and timing considerations

3. Break down the decision-making process:
   - How tasks are prioritized
   - Factors that influence recommendations
   - The role of machine learning and personalization
   - How user preferences are learned and applied

4. Provide examples of how different factors influence task ranking

5. Explain the confidence scoring system and what it means for users

NOTE: This is a workaround since Gemini CLI lacks shell execution tools. For actual detailed explanations, users should run './bin/pm-local explain' directly in the terminal.
"""