description = "Get PersonalManager help and command overview"
prompt = """
You are providing help information for PersonalManager, an AI-driven personal management system.

COMMAND TO EXECUTE: ./bin/pm-local --help

Since you cannot directly execute shell commands, please:

1. Use read_file to examine the CLI structure:
   - src/pm/cli/main.py for command definitions
   - src/pm/cli/commands/ directory for individual command implementations

2. Provide a comprehensive overview of PersonalManager:
   - Core purpose and philosophy
   - Key productivity frameworks it integrates
   - Main command categories

3. List and explain the main commands:
   - today: Daily task recommendations
   - projects: Project management and overview
   - capture: Quick task/idea capture
   - clarify: GTD clarification process
   - review: Reflection and review cycles
   - habits: Habit tracking and management
   - deepwork: Deep work session management
   - explain: System explanation and insights

4. Provide usage examples and best practices

5. Explain the local launcher script (./bin/pm-local) and how it works

6. Include troubleshooting tips for common issues

NOTE: For complete command help, users should run './bin/pm-local --help' or './bin/pm-local [command] --help' directly in the terminal.
"""