description = "Get PersonalManager projects overview and status"
prompt = """
You are executing PersonalManager's 'projects' command which provides project status overview and management capabilities.

COMMAND TO EXECUTE: ./bin/pm-local projects overview

Since you cannot directly execute shell commands, please:

1. Use read_file to examine the test_projects directory
2. Look for PROJECT_STATUS.md files in each project subdirectory
3. Read any project configuration or status files you find
4. Check src/pm/tools/project_tools.py for project management logic
5. Provide a comprehensive project overview including:
   - Project names and current status
   - Key milestones and deadlines
   - Progress indicators
   - Any blockers or issues

If you find project data, analyze and summarize it in a format similar to what 'pm projects overview' would display.

NOTE: This is a workaround since Gemini CLI lacks shell execution tools. For actual usage, users should run './bin/pm-local projects overview' directly in the terminal.
"""