description = "Get today's personalized task recommendations from PersonalManager"
prompt = """
You are executing PersonalManager's 'today' command which provides intelligent daily task recommendations based on multiple productivity frameworks.

COMMAND TO EXECUTE: ./bin/pm-local today

Since you cannot directly execute shell commands, please:

1. Use read_file to examine the current project structure
2. Look for task-related files in src/pm/ directory
3. Check for any existing task data or configuration files
4. Provide insights about what the 'today' command would typically show:
   - Top 3 recommended tasks based on priority, context, and urgency
   - Intelligent scoring using OKR, 4DX, GTD, Atomic Habits, and other frameworks
   - Context-aware recommendations based on current situation

If you find task data files, analyze them and provide a mock output similar to what 'pm today' would produce.

NOTE: This is a workaround since Gemini CLI lacks shell execution tools. For actual usage, users should run './bin/pm-local today' directly in the terminal.
"""