# Health Probe Configuration for OBS-O3
# Defines endpoints, thresholds, and monitoring parameters

# Global settings
global:
  probe_interval: 30  # seconds
  timeout: 10         # seconds
  retry_attempts: 3
  retry_delay: 5      # seconds
  log_retention_hours: 48
  slo_target: 99.5    # percentage

# Critical endpoints to monitor
endpoints:
  - name: "api-server"
    url: "http://localhost:8001"
    health_path: "/health"
    timeout: 10
    critical: true
    description: "Main API server health endpoint"
    expected_response:
      status_code: 200
      content_type: "application/json"
      required_fields: ["status", "timestamp"]
    thresholds:
      response_time_ms: 1000
      error_rate_threshold: 1.0  # percentage
      consecutive_failures: 3

  - name: "api-server-ready"
    url: "http://localhost:8001"
    health_path: "/ready"
    timeout: 10
    critical: true
    description: "API server readiness probe"
    expected_response:
      status_code: 200
      content_type: "application/json"
    thresholds:
      response_time_ms: 500
      error_rate_threshold: 0.5
      consecutive_failures: 2

  - name: "api-server-metrics"
    url: "http://localhost:8001"
    health_path: "/metrics"
    timeout: 15
    critical: false
    description: "Prometheus metrics endpoint"
    expected_response:
      status_code: 200
      content_type: "text/plain"
    thresholds:
      response_time_ms: 2000
      error_rate_threshold: 5.0
      consecutive_failures: 5

  - name: "api-docs"
    url: "http://localhost:8001"
    health_path: "/docs"
    timeout: 10
    critical: false
    description: "API documentation endpoint"
    expected_response:
      status_code: 200
      content_type: "text/html"
    thresholds:
      response_time_ms: 3000
      error_rate_threshold: 10.0
      consecutive_failures: 10

  - name: "api-openapi"
    url: "http://localhost:8001"
    health_path: "/openapi.json"
    timeout: 10
    critical: false
    description: "OpenAPI specification endpoint"
    expected_response:
      status_code: 200
      content_type: "application/json"
    thresholds:
      response_time_ms: 1500
      error_rate_threshold: 5.0
      consecutive_failures: 5

# SLO calculation windows
slo_windows:
  - name: "1hour"
    duration_minutes: 60
    weight: 1.0
  - name: "6hour"
    duration_minutes: 360
    weight: 1.5
  - name: "24hour"
    duration_minutes: 1440
    weight: 2.0

# Alert thresholds
alerts:
  critical:
    availability_threshold: 95.0  # percentage
    response_time_p99: 5000       # milliseconds
    consecutive_failures: 5
    notification_channels: ["slack", "email"]

  warning:
    availability_threshold: 98.0  # percentage
    response_time_p99: 2000       # milliseconds
    consecutive_failures: 3
    notification_channels: ["slack"]

# Data retention and cleanup
retention:
  raw_logs_hours: 48
  aggregated_metrics_hours: 168  # 7 days
  slo_reports_days: 30
  archive_old_data: true

# Monitoring and reporting
monitoring:
  dashboard_update_interval: 60  # seconds
  report_generation_interval: 3600  # seconds (1 hour)
  health_check_summary_interval: 300  # seconds (5 minutes)

  # Export formats
  export_formats:
    - "json"
    - "prometheus"
    - "csv"

# Simulation parameters (for testing)
simulation:
  enable_failure_injection: false
  failure_probability: 0.5  # percentage
  failure_duration_range: [10, 300]  # seconds
  maintenance_windows:
    - start: "02:00"
      end: "04:00"
      frequency: "weekly"
      day: "sunday"